from __future__ import annotations

import time
import webbrowser
from pathlib import Path
from typing import Iterable

import httpx
from yt_dlp.cookies import extract_cookies_from_browser

from video_sum_service.context import settings_manager

BILIBILI_LOGIN_URL = "https://passport.bilibili.com/login"
BILIBILI_QRCODE_GENERATE_URL = "https://passport.bilibili.com/x/passport-login/web/qrcode/generate"
BILIBILI_QRCODE_POLL_URL = "https://passport.bilibili.com/x/passport-login/web/qrcode/poll"
BILIBILI_BROWSER_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
    ),
    "Referer": "https://www.bilibili.com/",
    "Origin": "https://www.bilibili.com",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
}
DEFAULT_BROWSER_CANDIDATES = ("chrome", "edge", "firefox")


class QuietYtdlpLogger:
    def debug(self, _message: str) -> None:
        return None

    def info(self, _message: str) -> None:
        return None

    def warning(self, _message: str) -> None:
        return None

    def error(self, _message: str) -> None:
        return None


def _clean_cookie_text(value: object) -> str:
    return str(value or "").replace("\t", "").replace("\r", "").replace("\n", "")


def _format_cookie_for_netscape(cookie) -> str:
    domain = _clean_cookie_text(getattr(cookie, "domain", ""))
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    cookie_path = _clean_cookie_text(getattr(cookie, "path", "") or "/")
    secure = "TRUE" if bool(getattr(cookie, "secure", False)) else "FALSE"
    expires = max(0, int(getattr(cookie, "expires", 0) or 0))
    name = _clean_cookie_text(getattr(cookie, "name", ""))
    value = _clean_cookie_text(getattr(cookie, "value", ""))
    return "\t".join([domain, include_subdomains, cookie_path, secure, str(expires), name, value])


def _bilibili_cookies(cookie_jar) -> list[object]:
    cookies = []
    for cookie in cookie_jar:
        domain = str(getattr(cookie, "domain", "") or "")
        name = str(getattr(cookie, "name", "") or "")
        value = str(getattr(cookie, "value", "") or "")
        if "bilibili.com" in domain and name and value:
            cookies.append(cookie)
    return cookies


def _has_login_cookie(cookies: Iterable[object]) -> bool:
    return any(str(getattr(cookie, "name", "") or "") == "SESSDATA" for cookie in cookies)


def _cookie_export_path() -> Path:
    return Path(settings_manager.current.data_dir) / "cookies" / "bilibili.txt"


def _write_bilibili_cookies(cookies: list[object]) -> str:
    cookies_file = _cookie_export_path()
    cookies_file.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by BiliSum from local browser Bilibili login cookies.",
        *[
            _format_cookie_for_netscape(cookie)
            for cookie in sorted(
                cookies,
                key=lambda item: (
                    str(getattr(item, "domain", "") or ""),
                    str(getattr(item, "path", "") or ""),
                    str(getattr(item, "name", "") or ""),
                ),
            )
        ],
        "",
    ]
    cookies_file.write_text("\n".join(lines), encoding="utf-8")
    return str(cookies_file)


def create_bilibili_login_qrcode() -> dict[str, object]:
    with httpx.Client(timeout=20, follow_redirects=True, headers=BILIBILI_BROWSER_HEADERS) as client:
        response = client.get(BILIBILI_QRCODE_GENERATE_URL)
    try:
        response.raise_for_status()
    except httpx.HTTPStatusError as exc:
        raise RuntimeError(f"B 站二维码生成失败：HTTP {response.status_code}，{response.text[:200]}") from exc
    payload = response.json()
    data = payload.get("data") if isinstance(payload, dict) else None
    if not isinstance(data, dict):
        raise RuntimeError("B 站二维码生成失败：响应格式无效。")
    url = str(data.get("url") or "").strip()
    qrcode_key = str(data.get("qrcode_key") or "").strip()
    if not url or not qrcode_key:
        raise RuntimeError("B 站二维码生成失败：缺少登录二维码参数。")
    return {
        "url": url,
        "qrcodeKey": qrcode_key,
        "expiresIn": 180,
    }


def poll_bilibili_login_qrcode(qrcode_key: str) -> dict[str, object]:
    key = str(qrcode_key or "").strip()
    if not key:
        raise RuntimeError("B 站二维码登录失败：缺少 qrcode_key。")

    with httpx.Client(timeout=20, follow_redirects=False, headers=BILIBILI_BROWSER_HEADERS) as client:
        response = client.get(BILIBILI_QRCODE_POLL_URL, params={"qrcode_key": key})
    try:
        response.raise_for_status()
    except httpx.HTTPStatusError as exc:
        raise RuntimeError(f"B 站二维码登录检查失败：HTTP {response.status_code}，{response.text[:200]}") from exc
    payload = response.json()
    data = payload.get("data") if isinstance(payload, dict) else None
    if not isinstance(data, dict):
        raise RuntimeError("B 站二维码登录失败：响应格式无效。")

    code = int(data.get("code") or 0)
    message = str(data.get("message") or payload.get("message") or "").strip()
    if code == 86101:
        return {"status": "pending", "message": message or "等待扫码。"}
    if code == 86090:
        return {"status": "scanned", "message": message or "已扫码，请在手机上确认登录。"}
    if code == 86038:
        return {"status": "expired", "message": message or "二维码已过期，请重新获取。"}
    if code != 0:
        raise RuntimeError(message or f"B 站二维码登录失败：状态码 {code}。")

    cookies = _bilibili_cookies(response.cookies.jar)
    if not _has_login_cookie(cookies):
        raise RuntimeError("B 站二维码已确认，但响应里没有可用登录态 cookies。")
    cookies_file = _write_bilibili_cookies(cookies)
    return {
        "status": "confirmed",
        "message": "B 站扫码登录已确认。",
        "cookiesFile": cookies_file,
        "cookieCount": len(cookies),
    }


def capture_bilibili_cookies_from_browser(
    *,
    browsers: Iterable[str] = DEFAULT_BROWSER_CANDIDATES,
    open_login_page: bool = True,
    timeout_seconds: float = 180,
    poll_interval_seconds: float = 3,
) -> dict[str, object]:
    if open_login_page:
        webbrowser.open(BILIBILI_LOGIN_URL)

    deadline = time.monotonic() + max(0, timeout_seconds)
    last_errors: list[str] = []
    browser_names = [browser for browser in browsers if str(browser or "").strip()]
    while True:
        for browser in browser_names:
            try:
                cookie_jar = extract_cookies_from_browser(browser, logger=QuietYtdlpLogger())
            except Exception as exc:  # yt-dlp raises several browser-specific exception classes.
                last_errors.append(f"{browser}: {exc}")
                continue

            cookies = _bilibili_cookies(cookie_jar)
            if not _has_login_cookie(cookies):
                continue

            cookies_file = _write_bilibili_cookies(cookies)
            return {
                "cookiesFile": cookies_file,
                "cookieCount": len(cookies),
                "browser": browser,
            }

        if time.monotonic() >= deadline:
            detail = "；".join(last_errors[-3:])
            suffix = f" 最近错误：{detail}" if detail else ""
            raise RuntimeError(
                "没有从本机浏览器读取到 B 站登录态。请确认已在 Chrome、Edge 或 Firefox 登录 B 站后重试。"
                + suffix
            )
        time.sleep(max(0.5, poll_interval_seconds))
